local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc(data) m=string.sub(data, 0, 550) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


local Player = game.Players.LocalPlayer
local Camera = game.Workspace.CurrentCamera
local RunService = game:GetService(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('ytXvDrJTNgFIkfVicoibWnqQIVNVZBzttAQvJUdRGyPTlPWhSlLSGERUBtkBsATmNhUmZDdMxIrShiHSACLjHlCBUhCjwKdKNrqIvtPByChBCDJhokTutWrQZnQgzEpqdTKbFQuseGwEytnQCBMcvPUZHnGvzYIIfrWLPOaHaqvlpQEhcvfrcXQFuUunCJMAVwAwDbffOCNujhoWRLYmNMChzZyYipewpQKXcrlmuADKyaKLEndGMEaehEZidwWKTVkLKbHfvxXmpHaHImocyyaqwssdlLYOfrHWcdVTGjIgfOOrjjvIKlJQOeDTkLlTRWpkwHpyTMuDCDeJoXfZCPonZGlTuIwYROIvHrMpNAfxlpvLHFbSsAmfHLhbIgtPBNIbSSxNErkRmYKButpiBwDOOSDDkGSSHpiAhMWuHoGWsfejUOfkkVcBmGSmYcJAzbNiQXBzlZoRCVkIrMhWvuGacUiijtlHxoQJrXyBRSUlnvDkOkqdiXTKissyqyjiiYqEDUdMbFMIXOAFtESkfACRuNuTbtMybVtjqfUnVuU2VydmljZQ=='))
local UserInputService = game:GetService(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('qNvXVFOWiBHLYOxZtOixmuXCzrvTAvwdTOGaLRuuyUkbxnNSUnttdUryNJpPpLndKIWoilZTkfMdvGYeNEvfPsrQDqkAtHMXyQZXufmJHxsKsNYGJxjXDqQPBWoEMGGMjPWmdAgyHrihpLrushhgyoJGMudHrOdzmOSvBOpttYNNVoLlDcxGAxgOfqirsPvKQagVXcYArUfkhxoJKbXMKkNmzVvETGsTntUijPpGxfYiDtFOYrojHnKvUpNXLbeGRTbzpFVSTLedWaRMbqGkfOxTPRNQPrKDifNnPejtuyTrFkKHNCvWBFCUyzZqQCaMXUFAZOjpeeMeVxvBCgCwQzXVSJJTTmsZqdQjqOuBwaqBfklBkCuuscmLFIlHuuCbNBUezFIkYEQRQSeSdGMkaoZVJUivmuAFHGmQdNqqCcnifjXCUoWwrRHJtNLveNhYQMNhuTrctoNtsmCebBTEyBxSNkYKXysWVnmDjXQvdmmKyfwnSDDhstFtMUKFiNGaxOWftmkvgJrGkiYAKomuqzOeOAYbiScepKFYhjVXNlcklucHV0U2VydmljZQ=='))

local CameraActive = false
local CameraSpeed = 50
local CameraHeightSpeed = 10
local Humanoid = Player.Character and Player.Character:FindFirstChild(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('ZmWEQIlSpwrKqDLjRbLhUArwWOZgVuRLNUlNwUkXWSQemGkfrIrkBUgZOdZrgntwCFtPVJgvhazXsUwIjPXyVjGEVseOBkyAbMZjWHTrHEwHEIhEidcOLiuGJmofnGqBoqSQOYdTxzpnuSrmePkAJgZBEGafUrjxfAtXJohKSlYuuvWRQyLnDOpcCDeZNCsUjpcCiwJdWUaffGSPySKOmMIHhOPakCpKzmUruUoYiwvlGVqdDXFhGNivvgkMcaUUAJjLsqVAFONGniCEVXaoSGnqjLPOcyEYdtgZaIJTmiyhZrsgfQXIJnQGGzKBDaxjNJONpgyWwIacboywKRTEezGUEAGESzBxIepJRgPRyFkJxzvCxBnuVUoRgYWVuyOcbUfVxOxTcIaToEmVIpBdgxOMlIGvaNnxGooqrtEwLfErzRFqlUQqyUpnpejwwCZDvWSloQHiFnsprbkfThZeXSmMEoSzzsrPauMfklxwwACZoyyTitZFrEzLvvYzxXWkmGWtkBXhxwefAkbSgysiFbsHnDmZjdJjawYUYRSHVtYW5vaWQ='))

if not Humanoid then
    warn(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('npIpjEFAuMoMpjCSBtrJreMmuixHheOGifjhZQBZAlGbdHQXIOGQgZSNtJzXikUGJcISgiIftAdjkTsqqmaMocFjAkmzyghJSofsXBFQDRytIVRfDxsCKmhNYfujqHcQRWlvIjNmjJOuqUGuZquwizzyYyMSVnrEtLvYSvTCjDPhYERpHhBjtnSkjtMWNegrEtIZHPPitFwahUZMwmjAcAtevotTlGbEvlgZFZNrkeWHAwdluPwsmJTpJmqlXhNXwqsPwdpHMsSaUTjdFqogjEMJqxzgSdotkHdyVLeVrqUKPQfRSSsAlXRtJLAmEflkAgvXucyPSlvxMnVWqgNINpcLXTIVHIQkPkDMERtozTLivUszZOPDDabVzddPcwVVFGsUbQkOAtvznlpkjPgvHFngNxwYBgJaLqxmPFgtKsDAuqWiNloGHUrXZSPTFcdXGnbOQVbLoURBLYBBpliRBImgtppRDlioVIWurqQLeaowEiHuBFkCSVphaLKWXEGGiGjpzjickowpdNXiKlFfdRGXmwniyjtXJiFNXZSHVtYW5vaWQgbm90IGZvdW5kIQ=='))
    return
end

local HiddenGui = Instance.new(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('SbuSUcDmopeVrXNDCBQPyJRUBxMjAUTjxHzeuRhseHODPsemKiGPaCJztFVIlPPBPTNhHolygTUZnLneoFPKRBawqkWXBWPsbxhCSwVCPVDeQXGywkbjKDNWGhzBXRRqhdcMPDjIJyzbHqCSFDNJTNuIbMQIepreReslGAASWpLhokfFfMfedyxWJbPNsKZZthdwZTXrNfeBiyyFpQxgDFmMkUamwdcFJdVTGVdLToLywpuYkBTLnrAnDhdHrLBnUxxNFWEBvcWJprDWfrbpGKEaCztnPOPOEtFiJamCHCqdervGaOYxhxOhavDaLUtjguKHnKPCPsHHZRcgqhrhaZSUidPeiuMumhbbaBrTZJePdtLLRDvUwiTUuBuSGXcMlXbbbeDDOtfgZqHHGIntsymsuyqzJTSaiBwHJVxZAASivtVjZHQOHsWxecDGTZbeDnLRfAILpHvqTlcyJxqWHqYcJdqNEJiwvAuPBopaSaxMtsLOUsUjpSSOirObsaUKAqrpDHeTjfmkOszickmJOiqCmFeaDcvFlCetAQU2NyZWVuR3Vp'))
HiddenGui.ResetOnSpawn = false
HiddenGui.Name = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('QjzMWMNtmyScbrSOGLbNJTmhYIsrZwtUngdNxGBsjDbcycYMGJCHUwIfAzzyEBNhWDiVdABvzEEabKEOfckMqVmeJaxYplKEXEgVXPQxzXybZPaIQIOHLFwFmnJVoEjhhctZmclngkVcPhvlceQUIHGFfRcRmygeOxueSBFKXWbJtgPXyocULwvhGkTvzCXdDVpxQUcfpUaXNAyZLWAMlzCqNGLxHljyxBLBGYUvYEDJFpeFdhwDdoWweCIvgnpaQWDTPpLIZqpYRNsevjIhmVfnhelQkJmunKhoiUaCQnSzcREMeHPhlVGxtnzHKOmyKhIoKhcskadhDLntOSVyNatbxaUYqPrgNsXNeoLTrVZNcEEmDfztaIvObiEdukikURBiwyslhyVewKdCPZcCNISnQEqFUvwXnnkvwzdsajxVyvHcZJbERQQjhYWxFIThGxxRThKHfgVrdeuMMssIrUNWAXLTFrifeHxuRfqqAVXzpXcxpQdwqrCJbQmtVTHBofDiJVHuqAXLHRSgTrvcAUTSMGmfmKkPNEznhySGlkZGVuXw==') .. tostring(math.random(1, 10000))
HiddenGui.Parent = game.CoreGui

local MenuFrame = Instance.new(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('nupjMJbiVaGyPLKKGkcPhEAqLjWspteeanZDRDbWdRPyGgdYIDjiCiAGellgumlXOuBZiFthwhJURDdmRsTozKaKdBgjjEykcwDjrabjgHjbcInNTpuKbYQdPYzcYbtWVZbLCSyaZOBjTaLWZSMpXTKawiQcmtpnWxfhNnjSLKTcxRtpbOXSAwgmxFyThrFuVJbigMlQNxVjaJqLGXaugXClvAxcxQwDtyQYHcCEqozuvTEDWggxygdItiHUCEiZExnXwwHtuhcCawwNVYuQnebEfGAjjeQCZDXijEjWygfIYiqTjlvtXwkxoiqGBbqjVHERQeoUHAaqsqYAXfWkwgLGOPHHDubAOJRTaMZmQOtvHUkUsUoEMLAiwAUMCxGvUYuwGcelfSYqklbiKrTWdCDeWIJhbfteDmfrpSmWUHBsOfUXlzLFUlXXAmbofDDJCxelztCheQBIVzXbUCbqrYdOcKWjfsdhWClnenOEmPLsBGHRFuLYtIulYvMSHJeJFCjgVaNcfszpPfyPCdKuVQKcYyjCBtEYvoerQPRnJhbWU='))
MenuFrame.Size = UDim2.new(0, 200, 0, 150)
MenuFrame.Position = UDim2.new(0.5, -100, 0.5, -75)
MenuFrame.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
MenuFrame.BorderSizePixel = 0
MenuFrame.Visible = true
MenuFrame.Parent = HiddenGui

local CameraButton = Instance.new(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('TfdxCtfBUhqJxnfSLMlkqeDXaCUhpWVQfIBlxLRsSIKJxinVlKUiCnvnHFhoHYAwKvOlfvjDUBbZqobpSLenMHmfsvsUIUAZpeFqhnNjzySOuItcwyGgGNjZSyCagpeSnNXXbidhtUhVonpACpbNGfvTOJWBQVjEhjKXzpVdViOSxCwbjKCxZXQgqNDVhzeXAaQHPxFEJPtgqNijTMtTAxNBZQqmBUZdwuJqKLjzBnmSKjljqWUQanycEfCresyOUneECSkoKnXeduCHiRJUheMOiAqPgpbphuxXkdEXSaZTRSxNAVJZgTJCBCoSigwfVLbevQcnLsRitGIaLmnGzjQCgNsVAnHunjUFWDDUjZvseBCDYgEWAOJcgYxgThvybjwdkQnRjUOQEuhHEqZXuJTdSfVHoggCKwmzKeJWIDLjswhIQxryBykfbjFZPVOWHwhELxfxuGRpbrDHAmZBWVTITqFzZNRoQWjhUlmtjGxMYofpvOZzCtdVtrttSYSUoxCmYJvrlHDEOxASILYnikqusrtwBAgjriHTZjVGV4dEJ1dHRvbg=='))
CameraButton.Size = UDim2.new(1, 0, 0, 40)
CameraButton.Position = UDim2.new(0, 0, 0, 0)
CameraButton.Text = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('WEskyrIQRVQBdiYNnwnPkEFEcMLEorASZdTiQBgjsikQasuEWjgoTCcxmOvktJrvYOXETVMzYxhiyGsckWaLcuCrqvbeEBmhjOpHQMQANczVLgqMjKBAAkweWniXtxgCIgNcJLnKzEWmuSPJAoNbxczUxSOSQQFfJsmXwxomnUMPpXrmKPQSPQdqIZJUgUIijxilrXaiGoqZKItjviVDVwGuIMdPXktuRPhwDxwvbwszlpiUnuWEYHsmiQTFexATYHxbbcEdRMDylrHQdWMPZkOjhkmzdMbpaEimypakhZzLuRhDbXHUUCmajohHFIbeokLVHAYPxzjNFIKbtrKHVJsVQnImrIrigGtiAVXydOrQDxUcplcXAURwzBjXeAycsZONDuSAVynKJAsqWphFvRsxIFNibCyKRXfhCfYLKmXFZNJEUMzCWXnrwNxCGJgSCruIntiIEBVzUFEJQQFVmzJBihcUaBLAtdvXDbrotFFrFlsCYFIIvBAIxmEGYamlYuBVgwYQpMSVyRpdwmsknHrdBeDmygmVcJipsXRW5hYmxlIENhbWVyYQ==')
CameraButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CameraButton.BackgroundColor3 = Color3.fromRGB(100, 100, 255)
CameraButton.BorderSizePixel = 0
CameraButton.Parent = MenuFrame

CameraButton.MouseButton1Click:Connect(function()
    CameraActive = not CameraActive
    if CameraActive then
        Camera.CameraType = Enum.CameraType.Scriptable
        Humanoid.WalkSpeed = 0
        CameraButton.Text = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('uQoENQDAcSOMGkBqgoVffKnUXAgUiUhddbbQrkrLYlJvupDtTUMaPWPTKSNIvsjPXxocSsMEiMiVTbVDpooabJAnAAAsPYhvPRvmjPxgdZjKMktASGPTqWIDHdQTNdlYAufHTqJDIWSHaxDgHJPojiSyTdLCiTTlfqxgFmsFwcaXhIhJwMlaGddpEuZRqMdcyoeVrhlqclUSnquaNfgZZzewAIXUphZRdOxfiJIrlLvSkoYPIeKudthZFMdVLeiLufAIkkEYltvORzyelabmfRckSnlExTNbZQJNZBSTaRIvtEmxsCKPRgKllnjeYYSFMzVJTbZvxrWITIsXJMszsOZASOOYsVMHDfWCaPrCgqaFXzyqIGYMmNWWzgddUItHaPrxsqMgamSfgCdFdtdCdkvJRzeZnAkkzzMgddqBxdaGqVTNfXkgfOFZBaouDOwxrxwBMllkdKILxqNuHbyEsQtaEVGFtJFCODQTXPKYlXKjywTzarjNOmWGyLLGKFACcGZwTmmaSoEvlmujTgpBUPwFRQFbfHPknfMuCbRGlzYWJsZSBDYW1lcmE=')
    else
        Camera.CameraType = Enum.CameraType.Custom
        Humanoid.WalkSpeed = 16
        CameraButton.Text = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('YMALSdKgIUKMTtYKmhQOjJnScpiJoKyMmynDUzlyIVTgFXuCKYigKXtOfyxyqwRORUSCGpfNsFGptnYQNohScnCdnsXvnMlutnFAXEVqbTWHuDXyRzzvUAwCCQPCOxZJBBHAskVDTnAOArWGtPJMQhUMBftzxcPAWtQiUjxWZXEjiCMkVOjqadXacHrzgeWPwTBlsgcBqAPQyVjYYUpASdzEhaWffUiKEoWOgmRqzDrArZiGsnTHTaUFWxaeaiXFdmnMYrwOhJUPIzntqyhWnwAySixhyEpfFcbAiyqSUdaxpAaTwTfuYKWkxeBfOalXHjaeHliPbhNdzACPfWipwvUcauCjRXhFPwHQzytXmlmwSiDUUerxBDmXVeoJTqOLAcMQImyjOYygkmbdejCYCuDqTjecddSBlIWxDwZVWLTcWWRvoCjKPNiSohLdcTRXGCfhtVPnmgsjSOVoIzcOoVnzwuDriHuLmDnfKilntmlKpBxztWwwplEPfPDBYtyHfeQiOQekQYskVejarhnZwKjkrLzRGtXpZddlpcRW5hYmxlIENhbWVyYQ==')
    end
end)

local SpeedButton = Instance.new(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('jslqKyUyvfwaLjhkfrjQLzrIoqseycCTtIYcRiQNMHsbTjniFDSxptwVkGEISrtCziTmwynfsmTdZaLsxZBNyPuKiPEYSniQBTHmwpleIEXUfbFjoRwFPuJCTKwBRiUzSYxGNZfcWOjgRXZcYdWpPHGSVXWqkbxExLTkBwqgkTcNSKyzKenCwCKFwZvNDDfuWTVuAlinheKSRnhfRhFMAajBkVAiZaATWtmGimYuJVdIUnjxqTWVcKjLVcuMQlYTKHAjtsiNZgJOjYXBiLwMAumhCRMREPeLWdssyHcszokJBrNYeoIpkvbNwEjZGrGTQsUCszHfxzIXjWNMPWaborkhTZFOAwFfwAUzRwUeXdsHFZZyWiMAdtXWMRhJUSJOmdcSuyLfyWaOhXiFlQGDoGmCSqsoZnxVQAkESdyyIqUbGUvWlcmwDbCeVLSdjlSjsIcTNCvJUdmwJtbvgqdQgXjMCPxPUVDiXPtWNaoCCYlTekxlDRvhKsvkuPvFMQlfPEXMqSxieASjqUIzqKPEmYukxhcevYQPYxtHmDVGV4dEJ1dHRvbg=='))
SpeedButton.Size = UDim2.new(1, 0, 0, 40)
SpeedButton.Position = UDim2.new(0, 0, 0, 50)
SpeedButton.Text = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('BBAMTOzjRrBwCDsDztmNmSrdsYTJTpdfXDXicOlGBqyhXIplbOLaxisTJkSHnurpppzvkuXlilWxMtmlxehxjOGJNhoKjLRfLpNpnfbuwVkZCbSkiRWgJchlosJIkxfTMEhUrLNnkeHwBbbJbTznxTryIHAwmWAGmBCDYNMOPuSzMwUIfsBrobjqpjNZddKosDHZnSwQleJZIacOqRfocCWJIMpqiiMPoPfMWpyKxjYbnXKxoylwCbWKrkqKCTxfuEeqbuNnlmzbjhvBhFpdpRpzaljohMuWceFNSYIiLHUVZZbKsTOfKMUPWTbmFTnHjTGonTqanaOeIIZRmSnOWOCtBBLfUILRMtSXgjtOTufcaRpvCENXBhwpaumLVXxiJxEwKtjnnoEfMHvlUmPlsIycldCNwnUVAmOndIpBQqrYxSZhOovdXzFvbIBnkVGfcHVkGXktTxxBhsTzhSwINlsaXmeotGZpoxEarNqZXmuxdFOZvbrqsMDvdyvZwbxvBNcCEqNJbXrqDEsQzUKKnqnGFzGRVSWduGGNPRU3BlZWQ6IA==') .. CameraSpeed
SpeedButton.TextColor3 = Color3.fromRGB(255, 255, 255)
SpeedButton.BackgroundColor3 = Color3.fromRGB(100, 100, 255)
SpeedButton.BorderSizePixel = 0
SpeedButton.Parent = MenuFrame

SpeedButton.MouseButton1Click:Connect(function()
    CameraSpeed = CameraSpeed == 50 and 100 or 50
    SpeedButton.Text = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('qahHouTUfvVmeogZAxypqIlpoxVfSOSvgzJqCvyKaxrooCYPtOMQeqKsHeIBnVloUfmRdEQEGAYigfQVftxzdjoQvtDtFQfIWlWISBncwqskCzmOyNvTrJAYiCGdBLblIGZZXswIJmUIKFrxuRyLWlQtkwizHgtRxpuCKnWtNvRDfgidXpVurtPKlyDxfjYFbUvUbZUmheNColImabbmBpGTfGZLUjeSSaHtihffrPgXZGfOaeTKtZJOjomjRGkIEKtIjFmQwCicMFLHjKfjLlqLVRWizvcqcAgvAbnyZILLKGYKIbxtnMYngowHapfDTEhikighMiHhozjuaeVhwBatiElpYCFsVSUxyhJXKNufxmchXVwANYwZvWPWRnOMpdeftDBLKPErNvpKUgSiLfLoWILPIfeqNAtWNrSEWMkUHgqpqekjMTREEGibmABCRSXTjHscNEDTNQoQGjPPrMxYYjDEoDcXzsMuEWOtpqGxuafPwweRNzBofDHXOOeHwTrbOkmDJOtZXXznHeAMeYjaoNuNBUgFXZUpfQU3BlZWQ6IA==') .. CameraSpeed
end)

local CloseButton = Instance.new(kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('VoRWUDPryXBTPWRnwtiuQMUFoiZoPjLEvzDAMbtnXYtNQQhHwEPLHiQcBZiOmLGHTLeqSANqanIDXDEYjosWxbjtTzhJoMtuttCVfHjyxrndurWbrpFWzCXnaFbAPTetLdNNcdMmRLofbludmFnuQJZUtQpQZkPUdkPRbXOkSfcgOsXjrATTrCxWQzWxMFkCAxqRYIGHxBTkKOwveuqvxsTJqqrLrohBrFFeyJDgcjxtjFcqkRGPwfkFuOiFMCABYVjcpNgtcbMotDObURLyPNXenHtAENsfhJfnNAHsKbxtghbTpZijqWedaUAsdyUCaCHvNzBHomzmgbftUKsKPEREFnlcGaFbYYFxbCDegoeQgaCuebhaPtBDzVJmjSFbpkhFSrXSrnUIKQaLYHxOxXMFSaseiNmbMgwofRHXonPxkqQplfkQeUUIhdWWgzvOkjWZYYhzNSufcXAfYmsCWJISksCrrIgBnWbnVnZanNvnGDNRMHBQNJuxSKKPdtwiFEryDPjKVeoNHheePxmzDLytIDeCrFZPVRtnlAVGV4dEJ1dHRvbg=='))
CloseButton.Size = UDim2.new(0, 40, 0, 40)
CloseButton.Position = UDim2.new(1, -40, 0, 0)
CloseButton.Text = kKBysyRTFBFfvVTbvrZZirlAMBhWDSvtyXNVxmjmmClXMgymLZzRoFTIbAVCVJWKRAJkkofxSciynVhOJpFEQPwyNuOBmQNc('MaUzOuPAxZKoEGUgclxtxQyJngrBwqBLeetVsppVjzAcJwZInSzPlDEnPmKUHNcqkmUZgdDWmkXPeWePrfkteBoISLujRoRIRpoFGSrdhjhXVFxdntaVhRQnlTXROJEXnupeRIIbhrQcCmEblqjnYhnTBPwULpIMubtHVrmLfSKoPGYaGfYkedDmhDkMevMrEFIxYxGqwoMDrFyBXuNJxKLolOipChgJNmbvYPBiWpAhzCsXWUyYTAIJNlJLRvNlvmFVqcXltxWbxosEhEVSUvcKiROVqrlwVhjZyKAUFjcwvScJJDxNbEitmZlnDWQTvBAkwuQTisndmdggdmQYJrjEqPCNzTIXccOmwCPAcrUraCBTCxbXNRLAYhvGhJmRNrbIikqmmXXewWWsUxojzMvYcgMokVNubMTJRZnfXPZGBNbdFAnkbBBHsyDdvBaqJCLxsEhTracFtvlJuPFlCrZKmsugvTHwQYKhRJcpiETbKOKKXAvJFJIudBbkxLwtKCxFsrMFBWGroZovDvgshwzNTcYnEWHaVSYtuDWA==')
CloseButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CloseButton.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
CloseButton.BorderSizePixel = 0
CloseButton.Parent = MenuFrame

CloseButton.MouseButton1Click:Connect(function()
    MenuFrame.Visible = false
end)

local function updateCamera()
    if not CameraActive then return end

    local moveDirection = Vector3.new(0, 0, 0)

    if UserInputService:IsKeyDown(Enum.KeyCode.W) then
        moveDirection += Camera.CFrame.LookVector
    elseif UserInputService:IsKeyDown(Enum.KeyCode.S) then
        moveDirection -= Camera.CFrame.LookVector
    end

    if UserInputService:IsKeyDown(Enum.KeyCode.A) then
        moveDirection -= Camera.CFrame.RightVector
    elseif UserInputService:IsKeyDown(Enum.KeyCode.D) then
        moveDirection += Camera.CFrame.RightVector
    end

    if UserInputService:IsKeyDown(Enum.KeyCode.Space) then
        moveDirection += Vector3.new(0, CameraHeightSpeed * RunService.Heartbeat:Wait(), 0)
    elseif UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) then
        moveDirection -= Vector3.new(0, CameraHeightSpeed * RunService.Heartbeat:Wait(), 0)
    end

    Camera.CFrame = Camera.CFrame + moveDirection * CameraSpeed * RunService.Heartbeat:Wait()
end

local function rotateCamera()
    if not CameraActive then return end

    local rotationX, rotationY = 0, 0

    if UserInputService:IsKeyDown(Enum.KeyCode.Left) then
        rotationY = -0.03
    elseif UserInputService:IsKeyDown(Enum.KeyCode.Right) then
        rotationY = 0.03
    end

    if UserInputService:IsKeyDown(Enum.KeyCode.Up) then
        rotationX = -0.03
    elseif UserInputService:IsKeyDown(Enum.KeyCode.Down) then
        rotationX = 0.03
    end

    Camera.CFrame = Camera.CFrame * CFrame.Angles(rotationX, rotationY, 0)
end

RunService.RenderStepped:Connect(function()
    updateCamera()
    rotateCamera()
end)    